### ISSUE TITLE
[BUG] Seemingly not suitable for larger applications

### ISSUE THREAD

**Issue by redstonedesigner** [Tert0/fastapi-discord#43]
When attempting to use this project as an APIRouter instead of using a FastAPI instance, the app displays the below error.  When attempting to mount as a "sub application", the same error is also displayed.

```
INFO:     127.0.0.1:61436 - "GET /callback?code=2iw4ojyJtoxT4f1eR0NDRzKV1yWUD5 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\fastapi\applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\starlette\applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\starlette\middleware\trustedhost.py", line 34, in __call__
    await self.app(scope, receive, send)
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\starlette\middleware\gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\starlette\exceptions.py", line 87, in __call__
    raise exc
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\starlette\exceptions.py", line 76, in __call__
    await self.app(scope, receive, sender)
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\starlette\routing.py", line 659, in __call__
    await route.handle(scope, receive, send)
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\starlette\routing.py", line 411, in handle
    await self.app(scope, receive, send)
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\fastapi\applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\starlette\applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\starlette\exceptions.py", line 87, in __call__
    raise exc
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\starlette\exceptions.py", line 76, in __call__
    await self.app(scope, receive, sender)
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\starlette\routing.py", line 659, in __call__
    await route.handle(scope, receive, send)
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\Users\redstonedesigner\Security Department\ASDA\app\routes\discord_auth.py", line 28, in callback
    token, refresh_token = await discord.get_access_token(code)
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\fastapi_discord\client.py", line 132, in get_access_token
    resp = await self.get_token_response(payload)
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\fastapi_discord\client.py", line 121, in get_token_response
    async with self.client_session.post(DISCORD_TOKEN_URL, data=payload) as resp:
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\aiohttp\client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\aiohttp\client.py", line 466, in _request
    with timer:
  File "D:\Users\Gabriel\AppData\Local\pypoetry\Cache\virtualenvs\asda-wqq2ZuQh-py3.10\lib\site-packages\aiohttp\helpers.py", line 701, in __enter__
    raise RuntimeError(
RuntimeError: Timeout context manager should be used inside a task
```

**Comment by AntyBD** [comment]
You find a fix of this problem?

**Comment by Tert0** [comment]
I could not reproduce this issue.
I hope https://github.com/Tert0/fastapi-discord/commit/4ca67b0621552c316ea694444124209055ca477c fixed this issue.
